#!/usr/bin/env python3
"""Patch the Android runner generated by `flutter create --platforms=android`.

The repository does not commit the platform runners yet (see docs/platform-setup.md).
CI generates android/ and this script applies the SARCADE-specific settings:

- INTERNET permission (the Flutter template only declares it for debug builds)
- foreground location permissions used by geolocator
- cleartext HTTP/WS, needed while the V0.1 server is reached as http://IP:8000 on a LAN
- application label "SARCADE"
- hardware features declared optional (touchscreen, GPS, location), so the
  Play Store also offers the app on Chromebooks without touch screen or GPS:
  a location permission otherwise implies a required GPS feature

The script is idempotent and fails loudly if the template changed shape.
"""
import re
import sys
from pathlib import Path

MANIFEST = Path("android/app/src/main/AndroidManifest.xml")
OPTIONAL_FEATURES = [
    "android.hardware.touchscreen",
    "android.hardware.location",
    "android.hardware.location.gps",
    "android.hardware.location.network",
]
PERMISSIONS = [
    "android.permission.INTERNET",
    "android.permission.ACCESS_NETWORK_STATE",
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_COARSE_LOCATION",
]


def main() -> int:
    if not MANIFEST.exists():
        print(f"error: {MANIFEST} not found, run flutter create first", file=sys.stderr)
        return 1
    xml = MANIFEST.read_text(encoding="utf-8")

    missing = [p for p in PERMISSIONS if f'android:name="{p}"' not in xml]
    features = [f for f in OPTIONAL_FEATURES if f'android:name="{f}"' not in xml]
    if missing or features:
        block = "".join(f'    <uses-permission android:name="{p}"/>\n' for p in missing)
        block += "".join(f'    <uses-feature android:name="{f}" android:required="false"/>\n' for f in features)
        xml, n = re.subn(r"(\n\s*<application\b)", "\n" + block.rstrip("\n") + r"\1", xml, count=1)
        if n != 1:
            print("error: <application> element not found", file=sys.stderr)
            return 1

    def patch_application(match: re.Match) -> str:
        tag = match.group(0)
        tag = re.sub(r'android:label="[^"]*"', 'android:label="SARCADE"', tag)
        if "android:usesCleartextTraffic" not in tag:
            tag = tag.replace("<application", '<application\n        android:usesCleartextTraffic="true"', 1)
        return tag

    xml, n = re.subn(r"<application\b[^>]*>", patch_application, xml, count=1)
    if n != 1:
        print("error: <application> element not found", file=sys.stderr)
        return 1

    MANIFEST.write_text(xml, encoding="utf-8")
    print(f"patched {MANIFEST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
