#!/usr/bin/env python3
"""Patch the web runner generated by `flutter create --platforms=web`.

The installable web app (PWA) is the main SARCADE channel on ChromeOS:
own resizable window, shelf icon, keyboard and mouse. This script sets the
manifest and the page for that use:

- name, French description and language, SARCADE colours
- display "standalone": the app opens in its own window, without browser UI
- orientation "any": usable in landscape and portrait, docked or split screen
- categories for the ChromeOS launcher

Idempotent, and fails loudly if the template changed shape.
"""
import json
import re
import sys
from pathlib import Path

MANIFEST = Path("web/manifest.json")
INDEX = Path("web/index.html")
THEME = "#173A6A"


def main() -> int:
    if not MANIFEST.exists() or not INDEX.exists():
        print("error: web/ runner not found, run flutter create first", file=sys.stderr)
        return 1
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if "icons" not in manifest:
        print("error: unexpected manifest.json content", file=sys.stderr)
        return 1
    manifest.update({
        "name": "SARCADE",
        "short_name": "SARCADE",
        "description": "Coordination terrain, cartographie et communications pour la sécurité civile",
        "lang": "fr",
        "start_url": ".",
        "scope": ".",
        "display": "standalone",
        "orientation": "any",
        "background_color": "#FFFFFF",
        "theme_color": THEME,
        "categories": ["navigation", "utilities", "productivity"],
    })
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    html = INDEX.read_text(encoding="utf-8")
    html = re.sub(r"<html[^>]*>", '<html lang="fr">', html, count=1)
    html = re.sub(r"<title>.*?</title>", "<title>SARCADE</title>", html, count=1, flags=re.S)
    html = re.sub(r'<meta name="description" content="[^"]*">',
                  '<meta name="description" content="SARCADE, coordination terrain et sécurité civile">', html, count=1)
    html = re.sub(r'<meta name="apple-mobile-web-app-title" content="[^"]*">',
                  '<meta name="apple-mobile-web-app-title" content="SARCADE">', html, count=1)
    if 'name="theme-color"' not in html:
        html = html.replace("</head>", f'  <meta name="theme-color" content="{THEME}">\n</head>', 1)
    INDEX.write_text(html, encoding="utf-8")
    print(f"patched {MANIFEST} and {INDEX}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
