#!/usr/bin/env python3
"""Patch the Windows runner generated by `flutter create --platforms=windows`.

- flutter_local_notifications_windows still includes <experimental/coroutine>,
  refused by recent MSVC (error STL1011) unless the deprecation is silenced:
  the definition is set for every target, plugins included.

Idempotent, and fails loudly if the template changed shape.
"""
import re
import sys
from pathlib import Path

CMAKE = Path("windows/CMakeLists.txt")
LINE = "add_compile_definitions(_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS)"


def main() -> int:
    if not CMAKE.exists():
        print(f"error: {CMAKE} not found, run flutter create first", file=sys.stderr)
        return 1
    text = CMAKE.read_text(encoding="utf-8")
    if LINE not in text:
        text, n = re.subn(r"(project\([^)]*\)\s*\n)", r"\1" + LINE + "\n", text, count=1)
        if n != 1:
            print("error: project() not found in windows/CMakeLists.txt", file=sys.stderr)
            return 1
        CMAKE.write_text(text, encoding="utf-8")
    print(f"patched {CMAKE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
