#!/usr/bin/env python3
"""Patch the iOS runner generated by `flutter create --platforms=ios`.

The repository does not commit the platform runners yet. CI generates ios/
and this script applies the SARCADE-specific settings to Runner/Info.plist:

- usage texts for location (geolocator), local network, photo library and camera,
  required by iOS before the system shows its permission prompts
- App Transport Security exception for plain HTTP/WS, needed while the V0.1
  server is reached as http://IP:8000 on a LAN (same as cleartext on Android)
- display name "SARCADE"

Idempotent, and fails loudly if the template changed shape.
"""
import plistlib
import sys
from pathlib import Path

PLIST = Path("ios/Runner/Info.plist")

USAGE = {
    "NSLocationWhenInUseUsageDescription":
        "SARCADE partage votre position avec le poste de commandement pendant l’événement.",
    "NSLocalNetworkUsageDescription":
        "SARCADE se connecte au serveur de l’événement sur le réseau local, même sans Internet.",
    "NSPhotoLibraryUsageDescription":
        "SARCADE permet de joindre des photos aux messages et aux fichiers partagés de l’événement.",
    "NSCameraUsageDescription":
        "SARCADE permet de prendre une photo et de l’envoyer en message au poste de commandement.",
}


def main() -> int:
    if not PLIST.exists():
        print(f"error: {PLIST} not found, run flutter create first", file=sys.stderr)
        return 1
    with PLIST.open("rb") as f:
        info = plistlib.load(f)
    if "CFBundleIdentifier" not in info:
        print("error: unexpected Info.plist content", file=sys.stderr)
        return 1
    info.update(USAGE)
    info["CFBundleDisplayName"] = "SARCADE"
    ats = info.setdefault("NSAppTransportSecurity", {})
    ats["NSAllowsArbitraryLoads"] = True
    ats["NSAllowsLocalNetworking"] = True
    with PLIST.open("wb") as f:
        plistlib.dump(info, f)
    print(f"patched {PLIST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
